### ISSUE TITLE
Implement Testing into Model

### ISSUE THREAD

**Issue by garmu** [magnusandy/ModelingJohnesDisease#1]

**Comment by add118** [comment]
-***Use action charts for the testing logic

-No need to test males
-Focus on NotPregnant and Pregnant states
-Testing happens in bulk and results are returned in bulk
(see Nates game of life vs. anylogic's game of life for how to implement this properly)
-Test at the transition to GrazingCalfs (October on the Calendar?)
-2 weeks for test results to return 

When to remove cows:
-when they test positive on tests
-regardless of whether pregnant or not

Notes:
-Fecal tests would not return any positive results for cows in Infected state
-Low rate of positive blood test rate for cows in Infected state

**Comment by add118** [comment]
Stretch goals:

-Cost effectiveness of testing
-Statistics for how many Susceptible cows get tested false positive and removed
-Also false negatives for all post-Infected states
-Cumulative testing results

**Comment by add118** [comment]
-Paramaterize the testing so that we can run multiple simulations with variations in things like tests per year, date of testing, delay in test results, etc,...

-What output does Cheryl want? Does she want total counts of cows found in particular states?

-Does she want cumulative data results? Design the testing action chart with this option in mind.

*Meeting with Nate, October 31st

**Comment by add118** [comment]
See initial commit c26edaf

Next implement timeplots and play with the Specificity and Sensitivity parameters to reach realistic disease removal rates.

**Comment by magnusandy** [comment]
We don't want to be playing around with Specificity and Sensitivity as they are fixed values

**Comment by add118** [comment]
Sensitivity is not a fixed value. It is a range according to this document: https://www.nmr.co.uk/uploads/files/files/testingforjohnes.pdf

In my implementation, I put sensitivity at the lower end of that range.

**Comment by add118** [comment]
For fecal testing, it also says "No false positives", yet we have Specificity at 0.999. I assumed that small percentage was present to account for errors so I left it in.

**Comment by magnusandy** [comment]
Gotcha, makes sense.
