### ISSUE TITLE
Reporting: Sensitivity Analyses

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#23]
4) Sensitivity Analyses. These could be
a) Structural sensitivity analyses (certain areas of the model are altered or disabled)
b) Parameter sensitivity analysis
c) Extreme value tests conducted (as part of model testing or out of curiousity). These would test
or seek to understand model behavior in "extreme" conditions (e.g. where one or more regions of the
model are disabled)

**Comment by add118** [comment]
Complete
