### ISSUE TITLE
Calibration - Optimization Experiment 

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#29]
Based on  Thursday November 24th Lecture.

We should setup an optimization experiment for Cheryl. Once she has data from a real life scenario, she can  insert it into a historical data table and then run the calibration experiment. We have done a lot of manual calibration, but to more closely match a real life scenario, Cheryl can run the calibration experiment against her future historical data to get the best values for certain parameters.

We need to think about what parameters are variable for the purposes of this calibration and then insert some fake historical data for now to test the experiment. 

I think this would be a great addition to our project and extremely useful for Cheryl's continues research. Let me know what you think.

- [ ] Create experiment

- [ ] Add fake historical data

- 

- 

- 

- [ ] Choose which parameters will vary in this experiment

**Comment by magnusandy** [comment]
I think its a good idea, depending on the time involved it might need to go on the backburner to be done if we have time.
