### ISSUE TITLE
Graph Clean-up

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#32]
Make the essential graphs bigger and more prominent, make the others smaller and move them somewhere else
- check spelling

**Comment by add118** [comment]
- [x] Grouping Graphs by Category (Testing, Population, Infection, etc,...)
- [x] Fixing typos
- [x] Making function and histogram names more readable
- [x] Making Graph names and axis more readable
- [x] Making Graphs larger

**Comment by add118** [comment]
Left TODO's in the descriptions of some charts which need to be addressed during our next meeting. Opening a new issue for those.
