### ISSUE TITLE
Osgood Comments

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#40]
- [x] Change age generation function to draw from a distribution
- [x] rename "child" variable in cow to "offspring"

**Comment by add118** [comment]
Was already a uniform distribution:

```
//Generates cows of the following starting ages (0,12,24,....,108 months)
if(time() == 0)
{
	int randomNum = uniform_discr(1,9);
	int age = (randomNum*12);
	return age;
}
else
{
	return 0;
}
```

**Comment by add118** [comment]
Changes made in 'staging_alex'. Merging into staging once 'staging' is committed after Jordan's changes.
