### ISSUE TITLE
Replace most simulation experiments: Add changeable parameters

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#42]
I want to make the model more presentable by adding changeable parameters to the Simulation Window (The one that says "JohnesDisease" and has a Run button). This will mean when Cheryl is sharing the model she can change initial parameters for the experiment by simply pressing the stop button and moving some sliders or clicking some check boxes. 

We can still keep many of the simulations we have as presets for easy initialization, but the changeable parameters makes it so the user wont have to open up a new simulation necessarily to see the effects of one or two parameter changes.

Details on how this is implemented: 
https://help.anylogic.com/index.jsp?topic=/com.xj.anylogic.help/html/controls/Experiment_Controls.html
https://youtu.be/pd8QMBL-ri4

**Comment by magnusandy** [comment]
while it is a good idea, If this will take a bunch of time, it should be put on the backburner as it was never really requested.

**Comment by add118** [comment]
Cheryl mentioned this independently and said it would be nice, but it's less of a priority than documentation.

**Comment by add118** [comment]
Made changes to BaselineWithBothTests Experiment. Once this is an agreed upon replacement for all the different simulations, we can start removing some of them (once we know all of their unique settings are changeable in the interface of BaselineWithBothTests ).
