### ISSUE TITLE
Fix Testing analytics graphs (true positive and true negative graphs)

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#46]
The proportions on the y axis result in funny numbers. we need to check the logic and be sure it's returning a proper proportion instead of the integer numbers we are currently getting. 

- [ ] Fixed True Positive Tests / total deceased
- [ ] Fixed True Negative Tests / total deceased

**Comment by garmu** [comment]
changed to true positives Per Month, gonna talk about it tomorrow

**Comment by add118** [comment]
Can you post a commit id that this was fixed in?
