### ISSUE TITLE
Notes from cheryls email

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#49]
- [x] In Main under “Space and Network” please change space dimensions to 1500 width * 700 height so cows can be visualized easier. 
·        Is it possible to put an outline around this space? 
·        Would it be possible to have an indicator of what month it is with the diagram?
·        Would it be possible to have an adjacent display (separate pen) for the adult bulls? (not necessary but useful)  If not some other separate indicator of the infection status of the adult bulls would be nice.
- [x] 2.      In the graphs in main – all graphs of changes over time should have years on the X axis please.
- [x] 3.      Could the removal graph in infection analytics be split into 2 to make it easier to see?  One with population control numbers and one with disease related numbers?
- [x] 4.      Under general population analytics, we probably don’t need the one with total deceased cows. (The disease control numbers from above could go there.)
- [x] 5.      What is weighted prevalence vs prevalence vs overall prevalence?
- [x] 6.      In the current version of the model the prevalence hovers around 5% and then goes down most times you run the model.  In the previous version, in the absence of control prevalence actually went up over time as one would expect.  Not sure what is different in this version but something seems to be different.  (I did run both several times to see if it was just stochastics.)
- [x] 7.      For testing analytics, we should see the test positives that have the disease /total animals with disease that tested at each point in time – so by definition this has to be a number between 0 and 1.  Basically it is just showing us the test sensitivity as it actually works in the model with either one or two tests.
 
- [x] 8.      Same applies to test negatives that really don’t have the disease / total number of true disease negatives tested.   (Note label here says   / Total diseased  -- This should be   / Total not diseased)  Again this should just be showing us test specificity as it is actually working in the model based on either one or two tests.
 
- [x] 9.      For the fecal test time to diagnosis and blood test time to diagnosis are these the results for the most recent test or a cumulative result?

**Comment by magnusandy** [comment]
Not sure if number 2 is possible, i think time plots default to model time.

**Comment by magnusandy** [comment]
5. 
Weighted prevalence includes the modifiers for subclinical and clinical cows, giving more weight to clinical, it is used in environmental contact calculation
Prevalence is the infected Females/total pop,
Overall prevelance is Infected Cows(male and female)/total pop

**Comment by add118** [comment]
2 isn't possible with Anylogic graphs. Better for Cheryl to just save the data to excel and then show a graph and proper axis there

**Comment by add118** [comment]
@magnusandy if you want to tackle 7. and 8. I'll do the Experiment interface stuff. Let me know what your plan is.

**Comment by garmu** [comment]
Working on 7 and 8, I should be done soon

**Comment by garmu** [comment]
TruePositive over population is so small, it makes sense to do just truePositive per month
