### ISSUE TITLE
BloodTestSubclinicalSensitivity and BloodTestClinicalSensitivity  backwards

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#54]
I believe the BloodTestSubclinicalSensitivity and BloodTestClinicalSensitivity values in BaselineWithBothTests are backwards. Please confirm this and then one of us can commit a fix. When this is closed I'll resolve the comment on page 20 of the document.

**Comment by magnusandy** [comment]
From an email from cheryl Oct 30, 2016
>The sensitivity #s as reported in the literature best apply to cows who are subclinical and clinical.  The sensitivity is the % of animals that are correctly classified as having the disease.  There should be some capacity to have the sensitivity for each test vary between the subclinical and clinical animals. (The fecal test will be more sensitive for the clinical animals & the blood test might actually be slightly less sensitive for the clinical animals.)

We confirmed with her the values we are currently using, they are the low/high values of the testing spectrum. i.e. the literature states blood testing has a sensitivity of 40-80% so we used those values.
