### ISSUE TITLE
Change Prevalence() statistic to be higher for calfs?

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#8]
If the cow agent is still weening, the prevalence may be higher for environmental transmission in reality. This about adding this feature by changing the return value of the Prevalence statistic in cows[..] to be dependent on whether the cow is in WeeningCalf.

**Comment by add118** [comment]
Instead of changing the prevalence, just half the rate for cows in GrazingCalf state and reduce to 0 when in Bulls, Pregnant and NonPregnant.

**Comment by garmu** [comment]
added GrazingCalfIntensityOfPrevalenceModifer and WeaningCalfIntensityOfPrevalenceModifer. Only Calves can get infected from enviroment.
